# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tk_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1202, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1202, 800))
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.a_tiles_label = QtWidgets.QLabel(self.central_widget)
        self.a_tiles_label.setGeometry(QtCore.QRect(12, 10, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.a_tiles_label.setFont(font)
        self.a_tiles_label.setObjectName("a_tiles_label")
        self.a_tiles_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.a_tiles_scroll_area.setEnabled(True)
        self.a_tiles_scroll_area.setGeometry(QtCore.QRect(10, 28, 385, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_tiles_scroll_area.sizePolicy().hasHeightForWidth())
        self.a_tiles_scroll_area.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.a_tiles_scroll_area.setPalette(palette)
        self.a_tiles_scroll_area.setAutoFillBackground(True)
        self.a_tiles_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.a_tiles_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.a_tiles_scroll_area.setWidgetResizable(True)
        self.a_tiles_scroll_area.setObjectName("a_tiles_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 366, 398))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.a_tiles_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.b_tiles_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.b_tiles_scroll_area.setEnabled(True)
        self.b_tiles_scroll_area.setGeometry(QtCore.QRect(408, 28, 385, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_tiles_scroll_area.sizePolicy().hasHeightForWidth())
        self.b_tiles_scroll_area.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.b_tiles_scroll_area.setPalette(palette)
        self.b_tiles_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.b_tiles_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.b_tiles_scroll_area.setWidgetResizable(True)
        self.b_tiles_scroll_area.setObjectName("b_tiles_scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 366, 398))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.b_tiles_scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.b_tiles_label = QtWidgets.QLabel(self.central_widget)
        self.b_tiles_label.setGeometry(QtCore.QRect(410, 10, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.b_tiles_label.setFont(font)
        self.b_tiles_label.setObjectName("b_tiles_label")
        self.c_tiles_label = QtWidgets.QLabel(self.central_widget)
        self.c_tiles_label.setGeometry(QtCore.QRect(808, 10, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_tiles_label.setFont(font)
        self.c_tiles_label.setObjectName("c_tiles_label")
        self.c_tiles_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.c_tiles_scroll_area.setEnabled(True)
        self.c_tiles_scroll_area.setGeometry(QtCore.QRect(806, 28, 385, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_tiles_scroll_area.sizePolicy().hasHeightForWidth())
        self.c_tiles_scroll_area.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.c_tiles_scroll_area.setPalette(palette)
        self.c_tiles_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.c_tiles_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.c_tiles_scroll_area.setWidgetResizable(True)
        self.c_tiles_scroll_area.setObjectName("c_tiles_scroll_area")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 366, 398))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.c_tiles_scroll_area.setWidget(self.scrollAreaWidgetContents_3)
        self.sobj_tiles_label = QtWidgets.QLabel(self.central_widget)
        self.sobj_tiles_label.setGeometry(QtCore.QRect(12, 442, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sobj_tiles_label.setFont(font)
        self.sobj_tiles_label.setObjectName("sobj_tiles_label")
        self.sobj_tiles_scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.sobj_tiles_scroll_area.setEnabled(True)
        self.sobj_tiles_scroll_area.setGeometry(QtCore.QRect(10, 460, 1181, 275))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sobj_tiles_scroll_area.sizePolicy().hasHeightForWidth())
        self.sobj_tiles_scroll_area.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.sobj_tiles_scroll_area.setPalette(palette)
        self.sobj_tiles_scroll_area.setAutoFillBackground(True)
        self.sobj_tiles_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sobj_tiles_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sobj_tiles_scroll_area.setWidgetResizable(True)
        self.sobj_tiles_scroll_area.setObjectName("sobj_tiles_scroll_area")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1179, 256))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.sobj_tiles_scroll_area.setWidget(self.scrollAreaWidgetContents_4)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport_All = QtWidgets.QMenu(self.menuFile)
        self.menuExport_All.setObjectName("menuExport_All")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuExtract = QtWidgets.QMenu(self.menuFile)
        self.menuExtract.setObjectName("menuExtract")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionA_Tiles = QtWidgets.QAction(MainWindow)
        self.actionA_Tiles.setObjectName("actionA_Tiles")
        self.actionB_Tiles = QtWidgets.QAction(MainWindow)
        self.actionB_Tiles.setObjectName("actionB_Tiles")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionC_Tiles = QtWidgets.QAction(MainWindow)
        self.actionC_Tiles.setObjectName("actionC_Tiles")
        self.actionExport_All = QtWidgets.QAction(MainWindow)
        self.actionExport_All.setObjectName("actionExport_All")
        self.actionStatic_Tiles = QtWidgets.QAction(MainWindow)
        self.actionStatic_Tiles.setObjectName("actionStatic_Tiles")
        self.actionOpen_Map = QtWidgets.QAction(MainWindow)
        self.actionOpen_Map.setObjectName("actionOpen_Map")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionData_Files = QtWidgets.QAction(MainWindow)
        self.actionData_Files.setObjectName("actionData_Files")
        self.menuExport_All.addAction(self.actionA_Tiles)
        self.menuExport_All.addAction(self.actionB_Tiles)
        self.menuExport_All.addAction(self.actionC_Tiles)
        self.menuExport_All.addAction(self.actionStatic_Tiles)
        self.menuExport_All.addSeparator()
        self.menuExport_All.addAction(self.actionExport_All)
        self.menuOpen.addAction(self.actionOpen_Map)
        self.menuExtract.addAction(self.actionData_Files)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuExport_All.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExtract.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TKViewer"))
        self.a_tiles_label.setText(_translate("MainWindow", "A Tiles"))
        self.b_tiles_label.setText(_translate("MainWindow", "B Tiles"))
        self.c_tiles_label.setText(_translate("MainWindow", "C Tiles"))
        self.sobj_tiles_label.setText(_translate("MainWindow", "Static Objects"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport_All.setTitle(_translate("MainWindow", "Export"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuExtract.setTitle(_translate("MainWindow", "Extract"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionA_Tiles.setText(_translate("MainWindow", "A Tiles to Bitmaps"))
        self.actionB_Tiles.setText(_translate("MainWindow", "B Tiles to Bitmaps"))
        self.actionHelp.setText(_translate("MainWindow", "About"))
        self.actionC_Tiles.setText(_translate("MainWindow", "C Tiles to Bitmaps"))
        self.actionExport_All.setText(_translate("MainWindow", "Export All to Bitmaps"))
        self.actionStatic_Tiles.setText(_translate("MainWindow", "Static Objects to Bitmaps"))
        self.actionOpen_Map.setText(_translate("MainWindow", "Map File (*.map)"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionData_Files.setText(_translate("MainWindow", "Data Files (*.dat)"))

